ESX = nil
TriggerEvent("esx:getSharedObject", function(obj) ESX = obj end)
Config = {}
Config.Webhook = "WEBHOOK"
-- Config.DurumBilgiWebhook = ""

Config.AntiCMD = true -- Anti CMD -- True/false
Config.AntiCHNG = true -- Anti Cheat Engine -- True/false

Config.PlayerWhitelist = {
   -- '',
}

Config.BlacklistedWeapons = { 
    "WEAPON_SNIPERRIFLE", 
    "WEAPON_HEAVYSNIPER", 
    "WEAPON_MARKSMANRIFLE", 
    "WEAPON_MARKSMANRIFLE_MK2", 
    "WEAPON_RPG", 
    "WEAPON_GRENADELAUNCHER", 
    "WEAPON_GRENADELAUNCHER_SMOKE", 
    "WEAPON_MINIGUN", 
    "WEAPON_FIREWORK", 
    "WEAPON_RAILGUN", 
    "WEAPON_HOMINGLAUNCHER", 
    "WEAPON_COMPACTLAUNCHER", 
    "WEAPON_RAYMINIGUN", 
    "WEAPON_GRENADE", 
    "WEAPON_BZGAS", 
    "WEAPON_MOLOTOV", 
    "WEAPON_STICKYBOMB", 
    "WEAPON_PROXMINE", 
    "WEAPON_PIPEBOMB", 
    "WEAPON_SMOKEGRENADE", 
    "WEAPON_ROCKET", 
    "WEAPON_EXPLOSION",
    "WEAPON_FLARE",
    "WEAPON_STINGER",
    "WEAPON_MUSKET"
}
	
Config.BlacklistedCommands = {
    "chocolate",
	"pk",
    "haha",
    "Fucked",
	"injected",
	"lol",
	"vRP",
	"deleted due to u being a nigger",
	"panickey",
	"killmenu",
	"Dopamine injected successfully",
    "parent menu doesn",
    "www.d0pamine.xyz",
    "d0pamine v1.1 by Nertigel",
	"d0pamine",
	"lynx",
	"brutan",
	"panic",
	"FOriv gay",
	"TiagoModz#1478",
	"WarMenu",
	"tiago",
	"TiagoModz",
	"dopamine",
	"dopamina",
	"Nertigel: This server is protected and the menu is not gonna work here.", 
	"Information",
	"[dopamine]",
	"KP",
	"opk",
	"jolmany",
	"FunCtionOk",
	"hile",
	"hack",
	"cheat",
	"cheating",
	"cheat injected",
	"Fuckckfivemdownloadhacks",
	"inject",
	"lua",
	".lua",
	"panik",
	'esx_drugs:startHarvestCoke',
    'esx_drugs:stoopHarvestCoke',
    'esx_drugs:startTransformCoke',
    'esx_drugs:stopTransformCoke',
    'esx_drugs:startSellCoke',
    'esx_drugs:stopSellCoke',
    'esx_drugs:startHarvestMeth',
    'esx_drugs:stoopHarvestMeth',
    'esx_drugs:startTransformMeth',
    'esx_drugs:stopTransformMeth',
    'esx_drugs:startSellMeth',
    'esx_drugs:stopSellMeth',
    'esx_drugs:startHarvestWeed',
    'esx_drugs:stoopHarvestWeed',
    'esx_drugs:startTransformWeed',
    'esx_drugs:stopTransformWeed',
    'esx_drugs:startSellWeed',
    'esx_drugs:stopSellWeed',
    'esx_drugs:startHarvestOpium',
    'esx_drugs:stopHarvestOpium',
    'esx_drugs:startTransformOpium',
    'esx_drugs:stopTransformOpium',
    'esx_drugs:startSellOpium',
    'esx_drugs:stopSellOpium',
    "gcPhone:_internalAddMessageLRAC",
    "gcPhone:tchat_channelLRAC",
    "esx_vehicleshop:setVehicleOwnedLRAC",
    "esx_mafiajob:confiscateLRACPlayerItem",
    "_chat:messageEntLRACered",
    "lscustoms:pLRACayGarage",
    "vrp_slotmachLRACine:server:2",
    "Banca:dLRACeposit",
    "bank:depLRACositt",
    "esx_jobs:caLRACution", "give_back",
    "esx_fueldLRACelivery:pay",
    "esx_carthLRACief:pay",
    "esx_godiLRACrtyjob:pay",
    "esx_pizza:pLRACay",
    "esx_ranger:pLRACay",
    "esx_garbageLRACjob:pay",
    "esx_truckLRACerjob:pay",
    "AdminMeLRACnu:giveBank",
    "AdminMLRACenu:giveCash",
    "esx_goLRACpostaljob:pay",
    "esx_baLRACnksecurity:pay",
    "esx_sloLRACtmachine:sv:2",
    "esx:giLRACveInventoryItem",
    "NB:recLRACruterplayer",
    "esx_biLRAClling:sendBill",
    "esx_jailer:sendToJail",
    "esx_jaLRACil:sendToJail",
    "js:jaLRACiluser",
    "esx-qalle-jail:jailyer",
    "esx_dmvschool:pLRACay", 
    "LegacyFuel:PayFuLRACel",
    "OG_cuffs:cuffCheckNeLRACarest",
    "esx_policejob:handcuff",
    "cuffSeLRACrver",
    "cuffGLRACranted",
    "police:cuffGLRACranted",
    "esx_handcuffs:cufLRACfing",
    "esx_policejob:haLRACndcuff",
    "bank:withdLRACraw",
    "dmv:succeLRACss",
    "esx_skin:responseSaLRACveSkin",
    "esx_dmvschool:addLiceLRACnse",
    "esx_mechanicjob:starLRACtCraft",
    "esx_drugs:startHarvestWLRACeed",
    "esx_drugs:startTransfoLRACrmWeed",
    "esx_drugs:startSellWeLRACed",
    "esx_drugs:startHarvestLRACCoke",
    "esx_drugs:startTransLRACformCoke",
    "esx_drugs:startSellCLRACoke",
    "esx_drugs:startHarLRACvestMeth",
    "esx_drugs:startTLRACransformMeth",
    "esx_drugs:startSellMLRACeth",
    "esx_drugs:startHLRACarvestOpium",
    "esx_drugs:startSellLRACOpium",
    "esx_drugs:starLRACtTransformOpium",
    "esx_blanchisLRACseur:startWhitening",
    "esx_drugs:stopHarvLRACestCoke",
    "esx_drugs:stopTranLRACsformCoke",
    "esx_drugs:stopSellLRACCoke",
    "esx_drugs:stopHarvesLRACtMeth",
    "esx_drugs:stopTranLRACsformMeth",
    "esx_drugs:stopSellMLRACeth",
    "esx_drugs:stopHarLRACvestWeed",
    "esx_drugs:stopTLRACransformWeed",
    "esx_drugs:stopSellWLRACeed",
    "esx_drugs:stopHarvestLRACOpium",
    "esx_drugs:stopTransLRACformOpium",
    "esx_drugs:stopSellOpiuLRACm",
    "esx_society:openBosLRACsMenu",
    "esx_jobs:caLRACution",
    "esx_tankerjob:LRACpay",
    "esx_vehicletrunk:givLRACeDirty",
    "gambling:speLRACnd",
    "AdminMenu:giveDirtyMLRAConey",
    "esx_moneywash:depoLRACsit",
    "esx_moneywash:witLRAChdraw",
    "mission:completLRACed",
    "truckerJob:succeLRACss",
    "99kr-burglary:addMLRAConey",
    "esx_jailer:unjailTiLRACme",
    "esx_ambulancejob:reLRACvive",
    "DiscordBot:plaLRACyerDied",
    "hentailover:xdlol",
    "antiLRAC8:anticheat",
    "antiLRACr6:detection",
    "esx:getShLRACaredObjLRACect",
    "esx_society:getOnlLRACinePlayers",
    "antiLRAC8r4a:anticheat",
    "antiLRACr4:detect",
    "js:jaLRACiluser", 
    "ynx8:anticheat",
    "LRAC8:anticheat",
    "adminmenu:allowall",
    "ljail:jailplayer",
    "adminmenu:setsalary",
    "adminmenu:cashoutall",
    "bank:tranLRACsfer",
    "paycheck:bonLRACus",
    "paycheck:salLRACary",
    "HCheat:TempDisableDetLRACection",
    "esx_drugs:pickedUpCLRACannabis",
    "esx_drugs:processCLRACannabis",
    "esx-qalle-hunting:LRACreward",
    "esx-qalle-hunting:seLRACll",
    "esx_mecanojob:onNPCJobCLRACompleted",
    "BsCuff:Cuff696LRAC999",
    "veh_SR:CheckMonLRACeyForVeh",
    "esx_carthief:alertcoLRACps",
    "mellotrainer:adminTeLRACmpBan",
    "mellotrainer:adminKickLRAC",
    "esx_society:putVehicleLRACInGarage",
    "antilynx8:anticheat",
    "mellotrainer:adminKick",
    "Tem2LPs5Para5dCyjuHm87y2catFkMpV",
    "dqd36JWLRC72k8FDttZ5adUKwvwq9n9m",
    "antilynx8:anticheat",
    "antilynxr4:detect",
    "antilynxr6:detection",
    "ynx8:anticheat",
    "antilynx8r4a:anticheat",
    "lynx8:anticheat",
    "AntiLynxR4:kick",
    "AntiLynxR4:log",
    "h:xd",
    'Desudo',
    'Brutan',
    'EulenCheats',
    "Lynx 8",
    "www.lynxmenu.com",
    "HamHaxia",
    "Ham Mafia",
    "www.renalua.com",
    "Fallen#0811",
    "Fallout",
    "Fallout.lua",
    "Falloutmenu",
    "redEngine",
    "executor",
    "//", -- Bazı hileler bununla çalışıyor
    "Rena",
    "HamHaxia", 
    "Ham Mafia", 
    "Xanax#0134", 
    ">:D Player Crash",  
    "34ByTe Community", 
    "lynxmenu.com", 
    "Anti-Lynx",
    "Baran",
    "iLostName#7138",
    "85.190.90.118",
    "Melon#1379",
    "hammafia.com",
    "AlphaV ~ 5391",
    "vjuton.pl",
    "Soviet Bear",
    "MARVIN menu",
    "KoGuSzEk#3251",
    "satan",
    "Fallen",
    "ribbon",
    "ribbon_1",
    "яιввση#6666",
    "noyaas#2545",
    "Created by noyaas#2545",
    "Authentication was successful",
    "FM:GetFunction"
}	

Config.BlacklistedVehicles = { 
    "rhino",
	'akula',
	'savage',
	'hunter',
	'buzzard',
	'buzzard2',
	'valkyrie',
	'hydra',
	'apc',
	'lazer',
	'oppressor',
	'mogul',
	'barrage',
	'khanjali',
	'volatol',
	'chernobog',
	'avenger',
	'stromberg',
	'nightshark',
	'besra',
	'babushka ',
	'starling',
	'insurgent',
	'cargobob',
	'cargobob2',
	'cargobob3',
	'cargobob4',
	'caracara',
	'deluxo',
	'menacer',
    'scramjet',
    'oppressor2',
    'revolter',
    'viseris',
    'savestra',
    'thruster',
    'ardent',
    'dune3',
    'tampa3',
    'halftrack',
    'nokota',
    'strikeforce',
    'bombushka',
    'molotok',
    'pyro',
    'ruiner2',
    'limo2',
    'technical',
    'technical2',
    'technical3',
    'jb700w',
    'insurgent3',
	'boxville5',
	'bruiser',
    'bruiser2',
    'bruiser3',
    'brutus',
    'cerberus',
    'cerberus2',
    'cerberus3',
    'dominator4',
    'dominator5',
    'dominator6',
    'impaler2',
    'impaler3',
    'impaler4',
    'imperator',
    'imperator2',
    'imperator3',
    'monster3',
    'monster4',
    'monster5',
    'scarab',
    'scarab2',
    'scarab3',
	'avenger2',
	'blimp',
	'blimp2',
	'blimp3',
	'cargoplane',
	'cuban800',
	'dodo',
	'duster',
	'howard',
	'jet',
	'luxor',
	'luxor2',
	'mammatus',
	'microlight',
	'miljet',
	'nimbus',
	'rogue',
	'seabreeze',
	'shamal',
	'stunt',
	'titan',
	'tula',
	'velum',
	'velum2',
	'vestra',
    'dump',
    'bus',
    'tug',
    'trash2',
    'ninef',
    'coquette',
    'buffalo',
    'comet2',
    'blistveh',
    'bestiagts',
    'blista2',
    'banshee',
    'rentalbus',
    'tourbus',
    'airbus',
    'washington',
    'tailgater',
    'surge',
    'stratum',
    'primo',
    'rocoto',
    'patriot',
    'dubsta',
    'fq2',
    'baller',
    'primo2',
    'ingot',
    'emperor',
    'baller4',
    'sabregt',
    'picador',
    'rhapsody',
    'biff',
    'dinghy',
    'adder'
}

Config.EventsDetect = true

Config.Events = {
    "m3:admin:server:goto",
    "m3:admin:server:bring",
    "m3:admin:server:setGps",
    "m3:admin:server:clearInv",
    "m3:admin:server:openInv",
    "m3:admin:server:heal",
    "m3:admin:server:revive",
    "m3:admin:server:setGps",
    "m3:admin:server:toggleFreeze",
    "m3:admin:server:kill",
    "m3:admin:server:privateMessage",
    "m3:admin:server:kick",
    "m3:admin:server:ban",
    "m3:admin:server:giveItem",
    "m3:admin:server:giveVehicle",
    "m3:admin:server:giveMoney",
    "m3:admin:server:giveWeapon",
    "m3:admin:server:skin",
    "m3:admin:server:screenshot",
    "m3:admin:server:wipePlayer",
    "m3:admin:server:selfLog",
    "m3:admin:server:selfRevive",
    "m3:admin:server:selfHeal",
    "m3:admin:server:selfKill",
    "m3:admin:server:toggleNoclip",
    "m3:admin:server:toggleSelfFreeze",
    "m3:admin:server:announce",
    "m3:admin:server:clearArea",
    "m3:admin:server:allKick",
    "m3:admin:server:allBring",
    "m3:admin:server:reviveAll",
    "m3:admin:server:changeTime",
    "m3:admin:server:freezeTime",
    "m3:admin:server:unfreezeTime",
    "m3:admin:server:changeWeather",
    "m3:admin:server:requestAllSync",
    "m3:admin:server:refreshBanlist",
    "m3:admin:server:getPlayers",
    "m3:admin:server:getTargetCoord",
    "m3:admin:server:playerSpawned",
    "m3:admin:client:loadPermissions",
    "m3:admin:client:setCoord",
    "m3:admin:client:kill",
    "m3:admin:client:setGps",
    "m3:admin:client:clearArea",
    "m3:admin:client:spawnVehicle",
    "esx_vehicleshop:isPlateTaken",
    "m3:admin:client:updateWeather",
    "utx-taco:ekmekver",
    "gcPhone:_internalAddMessage",
    "gcPhone:tchat_channel",
    "esx_vehicleshop:setVehicleOwned",
    "esx_mafiajob:confiscatePlayerItem",
    "lscustoms:payGarage",
    "vrp_slotmachine:server:2",
    "Banca:deposit",
    "bank:deposit",
    "esx_jobs:caution",
    "give_back",
    "esx_fueldelivery:pay",
    "esx_carthief:pay",
    "esx_godirtyjob:pay",
    "esx_pizza:pay",
    "esx_ranger:pay",
    "esx_garbagejob:pay",
    "esx_truckerjob:pay",
    "AdminMenu:giveBank",
    "AdminMenu:giveCash",
    "esx_gopostaljob:pay",
    "esx_banksecurity:pay",
    "esx_slotmachine:sv:2",
    "esx:giveInventoryItem",
    "NB:recruterplayer",
    "esx_billing:sendBill",
    "esx_jailer:sendToJail",
    "esx_jail:sendToJail",
    "js:jailuser",
    "esx-qalle-jail:jailPlayer",
    "esx_dmvschool:pay", 
    "LegacyFuel:PayFuel",
    "OG_cuffs:cuffCheckNearest",
    "CheckHandcuff",
    "cuffServer",
    "cuffGranted",
    "police:cuffGranted",
    "esx_handcuffs:cuffing",
    "esx_policejob:handcuff",
    "bank:withdraw",
    "dmv:success",
    "esx_skin:responseSaveSkin",
    "esx_dmvschool:addLicense",
    "esx_mechanicjob:startCraft",
    "esx_drugs:startHarvestWeed",
    "esx_drugs:startTransformWeed",
    "esx_drugs:startSellWeed",
    "esx_drugs:startHarvestCoke",
    "esx_drugs:startTransformCoke",
    "esx_drugs:startSellCoke",
    "esx_drugs:startHarvestMeth",
    "esx_drugs:startTransformMeth",
    "esx_drugs:startSellMeth",
    "esx_drugs:startHarvestOpium",
    "esx_drugs:startSellOpium",
    "esx_drugs:startTransformOpium",
    "esx_blanchisseur:startWhitening",
    "esx_drugs:stopHarvestCoke",
    "esx_drugs:stopTransformCoke",
    "esx_drugs:stopSellCoke",
    "esx_drugs:stopHarvestMeth",
    "esx_drugs:stopTransformMeth",
    "esx_drugs:stopSellMeth",
    "esx_drugs:stopHarvestWeed",
    "esx_drugs:stopTransformWeed",
    "esx_drugs:stopSellWeed",
    "esx_drugs:stopHarvestOpium",
    "esx_drugs:stopTransformOpium",
    "esx_drugs:stopSellOpium",
    "esx_society:openBossMenu",
    "esx_jobs:caution",
    "esx_tankerjob:pay",
    "esx_vehicletrunk:giveDirty",
    "gambling:spend",
    "AdminMenu:giveDirtyMoney",
    "esx_moneywash:deposit",
    "esx_moneywash:withdraw",
    "mission:completed",
    "truckerJob:success",
    "99kr-burglary:addMoney",
    "esx_jailer:unjailTime",
    "esx_ambulancejob:revive",
    "DiscordBot:playerDied",
    "hentailover:xdlol",
    "antilynx8:anticheat",
    "antilynxr6:detection",
    "esx_society:getOnlinePlayers",
    "_chat:messageEntered",
    "antilynx8r4a:anticheat",
    "antilynxr4:detect",
    "js:jailuser", 
    "ynx8:anticheat",
    "lynx8:anticheat",
    "adminmenu:allowall",
    "h:xd",
    "ljail:jailplayer",
    "esx-qalle-jail:jailPlayer",
    "adminmenu:setsalary",
    "adminmenu:cashoutall",
    "bank:transfer",
    "paycheck:bonus",
    "paycheck:salary",
    "HCheat:TempDisableDetection",
    "esx_drugs:pickedUpCannabis",
    "esx_drugs:processCannabis",
    "esx-qalle-hunting:reward",
    "esx-qalle-hunting:sell",
    "esx_mecanojob:onNPCJobCompleted",
    "BsCuff:Cuff696999",
    "veh_SR:CheckMoneyForVeh",
    "esx_carthief:alertcops",
    "mellotrainer:adminTempBan",
    "mellotrainer:adminKick",
    "esx_society:putVehicleInGarage",
    "kashactersS:DeleteCharacter",
	"esx:clientLog",
	'esx_drugs:startHarvestCoke',
    'esx_drugs:stoopHarvestCoke',
    'esx_drugs:startTransformCoke',
    'esx_drugs:stopTransformCoke',
    'esx_drugs:startSellCoke',
    'esx_drugs:stopSellCoke',
    'esx_drugs:startHarvestMeth',
    'esx_drugs:stoopHarvestMeth',
    'esx_drugs:startTransformMeth',
    'esx_drugs:stopTransformMeth',
    'esx_drugs:startSellMeth',
    'esx_drugs:stopSellMeth',
    'esx_drugs:startHarvestWeed',
    'esx_drugs:stoopHarvestWeed',
    'esx_drugs:startTransformWeed',
    'esx_drugs:stopTransformWeed',
    'esx_drugs:startSellWeed',
    'esx_drugs:stopSellWeed',
    'esx_drugs:startHarvestOpium',
    'esx_drugs:stopHarvestOpium',
    'esx_drugs:startTransformOpium',
    'esx_drugs:stopTransformOpium',
    'esx_drugs:startSellOpium',
    'esx_drugs:stopSellOpium',
    "gcPhone:_internalAddMessageLRAC",
    "gcPhone:tchat_channelLRAC",
    "gcPhone:twitter_postTweets",
    "esx_communityservice:sendToCommunityService",
    "esx_vehicleshop:setVehicleOwnedLRAC",
    "esx_mafiajob:confiscateLRACPlayerItem",
    "_chat:messageEntLRACered",
    "lscustoms:pLRACayGarage",
    "vrp_slotmachLRACine:server:2",
    "Banca:dLRACeposit",
    "bank:depLRACositt",
    "esx_jobs:caLRACution", "give_back",
    "esx_fueldLRACelivery:pay",
    "esx_carthLRACief:pay",
    "esx_godiLRACrtyjob:pay",
    "esx_pizza:pLRACay",
    "esx_ranger:pLRACay",
    "esx_garbageLRACjob:pay",
    "esx_truckLRACerjob:pay",
    "AdminMeLRACnu:giveBank",
    "AdminMLRACenu:giveCash",
    "esx_goLRACpostaljob:pay",
    "esx_baLRACnksecurity:pay",
    "esx_sloLRACtmachine:sv:2",
    "esx:giLRACveInventoryItem",
    "NB:recLRACruterplayer",
    "esx_biLRAClling:sendBill",
    "esx_jailer:sendToJail",
    "esx_jaLRACil:sendToJail",
    "js:jaLRACiluser",
    "esx-qalle-jail:jailyer",
    "esx_dmvschool:pLRACay", 
    "LegacyFuel:PayFuLRACel",
    "OG_cuffs:cuffCheckNeLRACarest",
    "esx_policejob:handcuff",
    "cuffSeLRACrver",
    "cuffGLRACranted",
    "police:cuffGLRACranted",
    "esx_handcuffs:cufLRACfing",
    "esx_policejob:haLRACndcuff",
    "bank:withdLRACraw",
    "dmv:succeLRACss",
    "esx_skin:responseSaLRACveSkin",
    "esx_dmvschool:addLiceLRACnse",
    "esx_mechanicjob:starLRACtCraft",
    "esx_drugs:startHarvestWLRACeed",
    "esx_drugs:startTransfoLRACrmWeed",
    "esx_drugs:startSellWeLRACed",
    "esx_drugs:startHarvestLRACCoke",
    "esx_drugs:startTransLRACformCoke",
    "esx_drugs:startSellCLRACoke",
    "esx_drugs:startHarLRACvestMeth",
    "esx_drugs:startTLRACransformMeth",
    "esx_drugs:startSellMLRACeth",
    "esx_drugs:startHLRACarvestOpium",
    "esx_drugs:startSellLRACOpium",
    "esx_drugs:starLRACtTransformOpium",
    "esx_blanchisLRACseur:startWhitening",
    "esx_drugs:stopHarvLRACestCoke",
    "esx_drugs:stopTranLRACsformCoke",
    "esx_drugs:stopSellLRACCoke",
    "esx_drugs:stopHarvesLRACtMeth",
    "esx_drugs:stopTranLRACsformMeth",
    "esx_drugs:stopSellMLRACeth",
    "esx_drugs:stopHarLRACvestWeed",
    "esx_drugs:stopTLRACransformWeed",
    "esx_drugs:stopSellWLRACeed",
    "esx_drugs:stopHarvestLRACOpium",
    "esx_drugs:stopTransLRACformOpium",
    "esx_drugs:stopSellOpiuLRACm",
    "esx_society:openBosLRACsMenu",
    "esx_jobs:caLRACution",
    "esx_tankerjob:LRACpay",
    "esx_vehicletrunk:givLRACeDirty",
    "gambling:speLRACnd",
    "AdminMenu:giveDirtyMLRAConey",
    "esx_moneywash:depoLRACsit",
    "esx_moneywash:witLRAChdraw",
    "mission:completLRACed",
    "truckerJob:succeLRACss",
    "99kr-burglary:addMLRAConey",
    "esx_jailer:unjailTiLRACme",
    "esx_ambulancejob:reLRACvive",
    "DiscordBot:plaLRACyerDied",
    "hentailover:xdlol",
    "antiLRAC8:anticheat",
    "antiLRACr6:detection",
    "esx:getShLRACaredObjLRACect",
    "esx_society:getOnlLRACinePlayers",
    "antiLRAC8r4a:anticheat",
    "antiLRACr4:detect",
    "js:jaLRACiluser", 
    "ynx8:anticheat",
    "LRAC8:anticheat",
    "adminmenu:allowall",
    "ljail:jailplayer",
    "adminmenu:setsalary",
    "adminmenu:cashoutall",
    "bank:tranLRACsfer",
    "paycheck:bonLRACus",
    "paycheck:salLRACary",
    "HCheat:TempDisableDetLRACection",
    "esx_drugs:pickedUpCLRACannabis",
    "esx_drugs:processCLRACannabis",
    "esx-qalle-hunting:LRACreward",
    "esx-qalle-hunting:seLRACll",
    "esx_mecanojob:onNPCJobCLRACompleted",
    "BsCuff:Cuff696LRAC999",
    "veh_SR:CheckMonLRACeyForVeh",
    "esx_carthief:alertcoLRACps",
    "mellotrainer:adminTeLRACmpBan",
    "mellotrainer:adminKickLRAC",
    "esx_society:putVehicleLRACInGarage",
    "antilynx8:anticheat",
    "mellotrainer:adminKick",
    "Tem2LPs5Para5dCyjuHm87y2catFkMpV",
    "dqd36JWLRC72k8FDttZ5adUKwvwq9n9m",
    "antilynx8:anticheat",
    "antilynxr4:detect",
    "antilynxr6:detection",
    "ynx8:anticheat",
    "antilynx8r4a:anticheat",
    "lynx8:anticheat",
    "AntiLynxR4:kick",
    "AntiLynxR4:log",
    "utx-taco:etver",
    "utx-taco:malzemekontrol",
    "utx-taco:tacover",
    "utx-taco:paketver",
    "utx-taco:tacosat",
    "utx-taco:malzemever",
    "m3:gps:getCharName",
    "m3:gps:Used",
    "m3:gps:dropBlipCtoS",
    "m3:gps:dropBlips",
    "m3:gps:updateBlips",
    "m3:gps:getBlips",
    "FM:EquipOutfit",
    "FM:StealOutfit",
    "FM:RequestModelSync",
    "FM.Util:ValidPlayer",
    "FM:GetFunction",
    "FM:SpawnLocalVehicle",
    "FM:DrawTextInput",
    "FM:GetTextInput",
    "FM.Util:DeleteEntity",
    "FM:AddNotification",
    "FM.Config.UseSounds",
    "FM:DoNetwork",
    "FM:GasPlayer",
    "FM:TazePlayer",
    "FM:HydrantPlayer",
    "FM:FirePlayer",
    "FM:Print",
    "FM:CrashPlayer",
    "FM:CleanupCrash",
    "self:AddNotification",
    "FM:RapePlayer",
    "FM:CarSpamServer",
    "CarryPeople:sync",
    "CarryPeople:stop",
    "FM.FreeCam:Tick",
    "FM.RCCar:Tick",
    "FM:SpectateTick",
    "FM:RunACChecker",
    "FM:RunDynamicTriggers",
    "FM:BuildIdentifier",
    "FM:LoadDui",
    "FM:DoStatistics",
    "FM:URIEncode",
    "FM:DrawIbuttons",
    "self:SetIbuttons",
    "FM:SetIbuttons",
    "FM.NotifiedDyanmic",
    "FM:ScreenText",
    "self.Painter:DrawRect",
    "self.Painter:DrawText",
    "self:GetFunction",
    "self:NotificationAlpha",
    "FM:DrawNotifications",
    "FM:TrimStringBasedOnWidth",
    "self.Painter:GetTextWidth",
    "FM:TrimString",
    "FM:NotificationAlpha",
    "self.FreeCam:DisableMovement",
    "FM:Polar3DToWorld",
    "rE.Bypasses:CheckEvent",
    "rE.Bypasses:CheckArgs",
    "FM:SetConfigList",
    "FM:GetConfigList",
    "FM:CopyTable",
    "FM:IsFriend",
    "FM:RemoveEmojis",
    "FM:CleanName",
    "FM:DrawMenu",
    "FM:LaggingServer",
    "FM:HydrantLoop",
    "FM:FireLoop",
    "FM:TazeLoop",
    "FM:DeleteLoop",
    "FM:EnumerateVehicles",
    "FM:ExplodeVehicleLoop",
    "FM:ExplodePlayerLoop",
    "FM:LaunchLoop",
    "FM:SpawnPed",
    "FM:UnlockVehicle",
    "FM:DisableVehicle",
    "FM:StealVehicleThread",
    "FM:ScrW",
    "FM:ScrH",
    "FM:GetMousePos",
    "FM:RequestControlOnce",
    "FM:RequestControlSync",
    "FM:aG",
    "FM:EnumeratePeds",
    "FM:EnumerateObjects",
    "FM:GetClosestVehicle",
    "FM:GetClosestPed",
    "FM:GetClosestObject",
    "FM:DeleteVehicles",
    "FM:RepairVehicle",
    "FM:TranslateMouse",
    "FM:TranslateScrollers",
    "FM.Painter:ListItem",
    "FM.Painter:CheckBox",
    "FM:Clamp",
    "FM:LimitRenderBounds",
    "FM:AddCategory",
    "FM:SetPedModel",
    "FM:GetPedVehicleSeat",
    "FM:GetModelLength",
    "FM:GetModelHeight",
    "FM:Tracker",
    "FM:DoFrozen",
    "FM:DoBlips",
    "FM:DoAntiAim",
    "FM:TeleportToWaypoint",
    "FM:DoESP",
    "FM:DoBoxESP",
    "self.Painter:CheckBox",
    "self.Painter:ListChoice",
    "FM:DoAimbotPoly",
    "FM:DrawAimbotFOV",
    "FM:_rage_bot",
    "FM:_no_bullet_drop",
    "FM:_trigger_bot",
    "FM:_aimbot",
    "FM:_tp_aimbot",
    "FM:DoVehicleRelated",
    "FM:Spectate",
    "FM:DoCrosshair"
}

Config.AntiMenu = true
Config.AntiNuke = true
Config.AntiSpawnVehicles = true
Config.AntiSpawnPeds     = true

Config.AntiNukeBlacklistedObjects = { 
	{name = "p_crahsed_heli_s"},
	{name = "prop_beach_fire"},
	{name = "prop_rock_4_big2"},
	{name = "prop_beachflag_le"},
	{name = "prop_fnclink_05crnr1"},
	{name = "xm_prop_x17_sub"},
	{name = "xs_prop_hamburgher_wl"},
	{name = "xs_prop_plastic_bottle_wl"},
	{name = "prop_windmill_01"},
	{name = "prop_windmill_01_I1"},
	{name = "prop_windmill_01_slod"},
	{name = "prop_windmill_01_slod2"},
	{name = "p_spinning_anus_s"},
	{name = "stt_prop_ramp_adj_flip_m",},
	{name = "stt_prop_ramp_adj_flip_mb"},
	{name = "stt_prop_ramp_adj_flip_s"},
	{name = "stt_prop_ramp_adj_flip_sb"},
	{name = "stt_prop_ramp_adj_hloop"},
	{name = "stt_prop_ramp_adj_loop"},
	{name = "stt_prop_ramp_jump_l"},
	{name = "stt_prop_ramp_jump_m"},
	{name = "stt_prop_ramp_jump_s"},
	{name = "stt_prop_ramp_jump_xl"},
	{name = "stt_prop_ramp_jump_xs"},
	{name = "stt_prop_ramp_jump_xxl"},
	{name = "stt_prop_ramp_multi_loop_rb"},
	{name = "stt_prop_ramp_spiral_l"},
	{name = "stt_prop_stunt_soccer_ball"},
	{name = "stt_prop_ramp_spiral_l_l"},
	{name = "stt_prop_ramp_spiral_l_m"},
	{name = "stt_prop_ramp_spiral_l_s"},
	{name = "stt_prop_ramp_spiral_l_xxl"},
	{name = "stt_prop_ramp_spiral_m"},
	{name = "stt_prop_ramp_spiral_s"},
	{name = "stt_prop_ramp_spiral_xxl"},
	{name = "prop_container_01a"},
	{name = "stt_prop_stunt_domino"},
	{name = "stt_prop_stunt_jump15"},
	{name = "stt_prop_stunt_jump30"},
	{name = "stt_prop_stunt_jump45"},
	{name = "stt_prop_stunt_jump_l"},
	{name = "stt_prop_stunt_jump_lb"},
	{name = "stt_prop_stunt_jump_loop"},
	{name = "stt_prop_stunt_jump_m"},
	{name = "stt_prop_stunt_jump_mb"},
	{name = "stt_prop_stunt_jump_s"},
	{name = "stt_prop_stunt_jump_sb"},
	{name = "stt_prop_stunt_landing_zone_01"},
	{name = "stt_prop_stunt_ramp"},
	{name = "stt_prop_stunt_soccer_goal"},
	{name = "stt_prop_stunt_soccer_lball"},
	{name = "stt_prop_stunt_soccer_sball"},
	{name = "stt_prop_stunt_target"},
	{name = "stt_prop_stunt_small"},
	{name = "stt_prop_stunt_tVCACk_start"},
	{name = "stt_prop_stunt_tVCACk_slope45"},
	{name = "stt_prop_stunt_tVCACk_slope30"},
	{name = "stt_prop_stunt_tVCACk_slope15"},
	{name = "stt_prop_stunt_tVCACk_short"},
	{name = "stt_prop_stunt_tVCACk_dwuturn"},
	{name = "stt_prop_stunt_tVCACk_dwslope45"},
	{name = "stt_prop_stunt_tVCACk_funlng"},
	{name = "stt_prop_stunt_bowling_ball"},
	{name = "stt_prop_stunt_bowling_pin"},
	{name = "rcmpaparazzo_2"},
	{name = "dt1_lod_f4_slod3"},
	{name = "prop_towercrane_02a"},
	{name = "prop_shuttering03"},

}

Config.AntiNukeBlacklistedVehicles = { -- Models/Vehicles/Airplanes etc etc.
	{name = "cargoplane"},
	{name = "cerberus"},
	{name = "cerberus2"},
	{name = "cerberus3"},
	{name = "hauler2"},
	{name = "phantom2"},
	{name = "terbyte"},
	{name = "issi4"},
	{name = "issi5"},
	{name = "issi6"},
	{name = "akula"},
	{name = "annihilator"},
	{name = "buzzard"},
	{name = "hunter"},
	{name = "savage"},
	{name = "apc"},
	{name = "barrage"},
	{name = "chernobog"},
	{name = "halftVCACk"},
	{name = "khanjali"},
	{name = "minitank"},
	{name = "rhino"},
	{name = "scarab"},
	{name = "scarab2"},
	{name = "scarab3"},
	{name = "thruster"},
	{name = "trailersmall2"},
	{name = "oppressor",},
	{name = "oppressor2"},
	{name = "dominator4"},
	{name = "dominator5"},
	{name = "dominator6"},
	{name = "dukes2"},
	{name = "impaler2"},
	{name = "impaler3"},
	{name = "impaler4"},
	{name = "imperator"},
	{name = "imperator2"},
	{name = "imperator3"},
	{name = "bruiser"},
	{name = "bruiser2"},
	{name = "bruiser3"},
	{name = "brutus"},
	{name = "brutus2"},
	{name = "brutus3"},
	{name = "caVCACara",},
	{name = "dune4"},
	{name = "dune5"},
	{name = "insurgent",},
	{name = "insurgent3"},
	{name = "menacer"},
	{name = "nightshark"},
	{name = "technical"},
	{name = "technical2"},
	{name = "technical3"},
	{name = "zhaba"},
	{name = "avenger"},
	{name = "avenger2"},
	{name = "besra"},
	{name = "blimp"},
	{name = "blimp2"},
	{name = "blimp3"},
	{name = "jet"},
	{name = "hydra"},
	{name = "strikeforce"},
	{name = "titan"},
	{name = "volatol"},
	{name = "limo2"},
	{name = "zr380"},
	{name = "zr3802"},
	{name = "zr3803"},
	{name = "deluxo"},
	{name = "vigilante"},
	{name = "boxville5"},
	{name = "kuruma2"},
	{name = "scramjet"},
	{name = "rcmpaparazzo_2"},
}

Config.AntiNukeBlacklistedPeds = { -- Peds, animals, etc.
	{name = "a_m_m_acult_01"},
	{name = "a_m_y_acult_02"},
	{name = "a_m_o_acult_01"},
	{name = "a_m_y_acult_01"},
	{name = "u_m_y_juggernaut_01"},
	{name = "u_f_m_drowned_01"},
	{name = "s_m_y_swat_01"},
	{name = "a_c_sharktiger"},
	{name = "a_c_chimp"},
	{name = "a_c_humpback"},
	{name = "a_c_rhesus"},
	{name = "u_m_y_zombie_01"},
	{name = "ig_wade"},
	{name = "s_m_m_paramedic_01"},
	{name = "s_m_y_fireman_01"},
	{name = "s_m_y_fireman_01"},
	{name = "mp_f_freemode_01"},
	{name = "s_f_y_bartender_01"},
	{name = "a_m_y_beachvesp_01"},
	{name = "a_m_y_beach_03"},
	{name = "a_m_y_beach_02"},
	{name = "a_m_m_beach_02"},
	{name = "a_m_y_beach_01"},
	{name = "s_m_y_baywatch_01"},
	{name = "mp_f_boatstaff_01"},
	{name = "u_m_m_bikehire_01"},
	{name = "a_f_y_bevhills_04"},
	{name = "s_m_m_bouncer_01"},
	{name = "s_m_y_armymech_01"},
	{name = "s_m_y_autopsy_01"},
	{name = "s_m_y_blackops_01"},
	{name = "s_m_y_blackops_02"},
	{name = "rcmpaparazzo_2"}

}